/**
 * Lista completa de idiomas suportados pelo WhatsApp Business API para templates.
 * Fonte: https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/
 */
export interface WhatsAppLanguageOption {
  value: string
  label: string
}

export const WHATSAPP_LANGUAGES: WhatsAppLanguageOption[] = [
  { value: 'pt_BR', label: 'Português (Brasil)' },
  { value: 'pt_PT', label: 'Português (Portugal)' },
  { value: 'en_US', label: 'Inglês (EUA)' },
  { value: 'en_GB', label: 'Inglês (Reino Unido)' },
  { value: 'es', label: 'Espanhol' },
  { value: 'es_AR', label: 'Espanhol (Argentina)' },
  { value: 'es_ES', label: 'Espanhol (Espanha)' },
  { value: 'es_MX', label: 'Espanhol (México)' },
  { value: 'fr', label: 'Francês' },
  { value: 'fr_FR', label: 'Francês (França)' },
  { value: 'fr_CA', label: 'Francês (Canadá)' },
  { value: 'de', label: 'Alemão' },
  { value: 'it', label: 'Italiano' },
  { value: 'nl', label: 'Holandês' },
  { value: 'ru', label: 'Russo' },
  { value: 'ja', label: 'Japonês' },
  { value: 'ko', label: 'Coreano' },
  { value: 'zh_CN', label: 'Chinês (Simplificado)' },
  { value: 'zh_TW', label: 'Chinês (Tradicional)' },
  { value: 'ar', label: 'Árabe' },
  { value: 'tr', label: 'Turco' },
  { value: 'pl', label: 'Polonês' },
  { value: 'sv', label: 'Sueco' },
  { value: 'da', label: 'Dinamarquês' },
  { value: 'nb', label: 'Norueguês' },
  { value: 'fi', label: 'Finlandês' },
  { value: 'el', label: 'Grego' },
  { value: 'id', label: 'Indonésio' },
  { value: 'ms', label: 'Malaio' },
  { value: 'th', label: 'Tailandês' },
  { value: 'vi', label: 'Vietnamita' },
  { value: 'hi', label: 'Hindi' },
  { value: 'he', label: 'Hebraico' },
  { value: 'uk', label: 'Ucraniano' },
  { value: 'cs', label: 'Tcheco' },
  { value: 'sk', label: 'Eslovaco' },
  { value: 'ro', label: 'Romeno' },
  { value: 'hu', label: 'Húngaro' },
  { value: 'hr', label: 'Croata' },
  { value: 'bg', label: 'Búlgaro' },
  { value: 'ca', label: 'Catalão' },
  { value: 'af', label: 'Africâner' },
  { value: 'sq', label: 'Albanês' },
  { value: 'az', label: 'Azerbaijano' },
  { value: 'bn', label: 'Bengali' },
  { value: 'bs', label: 'Bósnio' },
  { value: 'et', label: 'Estoniano' },
  { value: 'ka', label: 'Georgiano' },
  { value: 'gu', label: 'Guzerate' },
  { value: 'ha', label: 'Hauçá' },
  { value: 'hy', label: 'Armênio' },
  { value: 'is', label: 'Islandês' },
  { value: 'kn', label: 'Canarês' },
  { value: 'kk', label: 'Cazaque' },
  { value: 'lv', label: 'Letão' },
  { value: 'lt', label: 'Lituano' },
  { value: 'mk', label: 'Macedônio' },
  { value: 'ml', label: 'Malaiala' },
  { value: 'mr', label: 'Marata' },
  { value: 'pa', label: 'Panjabi' },
  { value: 'sr', label: 'Sérvio' },
  { value: 'si', label: 'Cingalês' },
  { value: 'sl', label: 'Esloveno' },
  { value: 'sw', label: 'Suaíli' },
  { value: 'ta', label: 'Tâmil' },
  { value: 'te', label: 'Télugo' },
  { value: 'tl', label: 'Filipino' },
  { value: 'ur', label: 'Urdu' },
  { value: 'uz', label: 'Usbeque' },
  { value: 'zu', label: 'Zulu' },
]
